name: Lotto Crawler

on:
  schedule:
    - cron: '0 22 * * 6'  # 매주 토요일 22:00
    - cron: '0 23 * * 6'  # 매주 토요일 23:00
  workflow_dispatch:  # 수동 실행 가능

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run crawler
      run: python src/crawler.py --latest
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lotto/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update lotto data" && git push) 